function downloadBlueprint(projectData, storeName) {
  const phases = [
    { key: 'phase1', icon: '🔍', title: 'Phase 1 — Niche Discovery' },
    { key: 'phase2', icon: '📦', title: 'Phase 2 — Digital Product Ideas' },
    { key: 'phase3', icon: '🏪', title: 'Phase 3 — Store Setup & Branding' },
    { key: 'phase4', icon: '📢', title: 'Phase 4 — Marketing Content' },
    { key: 'phase5', icon: '🚀', title: 'Phase 5 — 30-Day Launch Plan' },
  ];

  const sections = phases
    .filter((p) => projectData[p.key]?.output)
    .map((p) => `# ${p.icon} ${p.title}\n\n${projectData[p.key].output}`)
    .join('\n\n---\n\n');

  const content = `# ${storeName} — Full Business Blueprint\nGenerated by ShopifyAgent.ai on ${new Date().toLocaleDateString()}\n\n---\n\n${sections}`;

  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${storeName.replace(/[^a-z0-9]/gi, '-').toLowerCase()}-blueprint.md`;
  a.click();
  URL.revokeObjectURL(url);
}

export default function CompletionScreen({ projectData, onRestart }) {
  const storeName = projectData?.phase3?.inputs?.storeName ||
    projectData?.phase2?.inputs?.niche ||
    'Your Business';

  const summaryCards = [
    {
      icon: '🔍',
      title: 'Niche Identified',
      desc: 'Your profitable market niche has been analyzed and validated.',
    },
    {
      icon: '📦',
      title: 'Products Designed',
      desc: '5 digital product ideas with full descriptions and pricing strategies.',
    },
    {
      icon: '🏪',
      title: 'Store Branded',
      desc: 'Complete brand identity, copy, and Shopify store content ready to go.',
    },
    {
      icon: '📢',
      title: 'Content Created',
      desc: 'Social posts, email sequences, ad copy, and content pillars generated.',
    },
    {
      icon: '🚀',
      title: 'Launch Plan Ready',
      desc: 'Day-by-day 30-day action plan to take your store from zero to revenue.',
    },
  ];

  const nextSteps = [
    'Create your Shopify account at shopify.com/free-trial',
    'Set up your store using the branding from Phase 3',
    'Create your first digital product using the Phase 2 ideas',
    'Schedule your social media content from Phase 4',
    'Follow your 30-day plan from Phase 5 — day by day',
  ];

  return (
    <div className="completion">
      <div className="completion-hero">
        <div className="completion-icon">🎉</div>
        <h1 className="completion-title">Your Business Blueprint is Complete!</h1>
        <p className="completion-subtitle">
          Every piece you need to launch {storeName} is ready. Time to take action.
        </p>
      </div>

      <div className="completion-cards">
        {summaryCards.map((card) => (
          <div key={card.title} className="completion-card">
            <div className="completion-card-icon">{card.icon}</div>
            <div className="completion-card-title">{card.title}</div>
            <div className="completion-card-desc">{card.desc}</div>
          </div>
        ))}
      </div>

      <div className="card" style={{ textAlign: 'left', marginTop: 8 }}>
        <div className="card-title">Your Next Steps</div>
        <ol style={{ paddingLeft: 20, display: 'flex', flexDirection: 'column', gap: 10 }}>
          {nextSteps.map((step, i) => (
            <li key={i} style={{ fontSize: 14, color: 'var(--gray-700)', lineHeight: 1.6 }}>
              {step}
            </li>
          ))}
        </ol>
      </div>

      <div className="completion-actions">
        <button className="btn btn-primary btn-lg" onClick={() => downloadBlueprint(projectData, storeName)}>
          ⬇ Download Full Blueprint
        </button>
        <button className="btn btn-secondary" onClick={onRestart}>
          ↺ Start Over with New Niche
        </button>
      </div>

      <p style={{ marginTop: 24, fontSize: 13, color: 'var(--gray-400)' }}>
        All outputs were AI-generated. Review and customize before going live.
      </p>
    </div>
  );
}
